/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-04-15 08:26:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>yeogiyo-main</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("        body {margin: 0; padding: 0;}\r\n");
      out.write("        /********** 전체컨테이너 **********/\r\n");
      out.write("        div#container\t{background-color:#F0F0F0; width:100%; margin:0 auto;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /********** header **********/\r\n");
      out.write("        header\t{background: red; height:80px; position:relative; padding:10px 0 0 0; }\r\n");
      out.write("        header h1 {margin-left:10px;  color:white;}\r\n");
      out.write("        #loginBtn {position:absolute; width:150px; height:30px; top: 30px; right: 300px;}\r\n");
      out.write("        #joinBtn {position:absolute; width:150px; height:30px; top: 30px; right: 100px;}\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        /********** search **********/\r\n");
      out.write("        section#search { background-color: yellow; float:left; width:100%; height: 150px; text-align: center;}\r\n");
      out.write("\r\n");
      out.write("        /********** content **********/\r\n");
      out.write("        section#content\t{ background-color:#F5F5F5; float:left; width:100%; min-height:500px; }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        /********** footer **********/\r\n");
      out.write("        footer { background-color:red; clear:both; height:75px; text-align:center;padding-top:40px;}\r\n");
      out.write("        footer p {color: white;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t <div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <h1>여기요</h1>\r\n");
      out.write("            \t<button type=\"button\" id=\"loginBtn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/memberlogin';\">로그인</button>\r\n");
      out.write("            \t<button type=\"button\" id=\"joinBtn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/memberEnroll';\">회원가입</button>\r\n");
      out.write("            \t<button type=\"button\" id=\"memberManage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/admin/memberManage';\">회원관리</button>\r\n");
      out.write("            \t<button type=\"button\" id=\"resMamage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/admin/resManage';\">가게관리</button>\r\n");
      out.write("            \t\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"search\">\r\n");
      out.write("\r\n");
      out.write("            <h2 align=\"center\">\"어디로 배달해 드릴까요?\"</h2>\r\n");
      out.write("            <form action=\"\"  method=\"GET\">\r\n");
      out.write("                <input type=\"text\" name=\"foodname\" id=\"foodname\">\r\n");
      out.write("                <input type=\"submit\" value=\"검색\">\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <section id=\"content\">\r\n");
      out.write("\r\n");
      out.write("            <h2 align=\"center\" style=\"margin-top:200px;\">content 부분</h2>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <footer>\r\n");
      out.write("            <p><strong>여기요</strong></p>\r\n");
      out.write("            <p>&lt;Copyright 1998-2021 <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
